package edu.hist.team3.catering.database;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Dish extends DatabaseRow {
	// Different columns of the Dish-table in the database:
	private final int id;						// id					INT			GENERATED BY DEFAULT AS IDENTITY
	private String name;						// name					VARCHAR(64)	NOT NULL
	private String category;					// category				VARCHAR(64)
	private double healthiness;					// healthiness			DOUBLE
	private double price;						// price				DOUBLE		NOT NULL
	private double defaultDiscount;				// default_discount		DOUBLE		NOT NULL
	private double longtermDiscount;			// longterm_discount	DOUBLE		NOT NULL
	
	
	private final DishResourceList resources;
	
	/**
	 * Creates a new instance of Dish.
	 * @param manager	The DatabaseManager for a connection to a database
	 * @param id		The ID of the dish
	 */
	protected Dish(DatabaseManager manager, int id){
		super(manager);
		this.id = id;
		resources = new DishResourceList(this);
	}
	
	/**
	 * Create a new default row in the Dish-table.
	 * @param manager	The DatabaseManager for a connection to a database
	 * @return A instance of Dish
	 * @throws SQLException
	 */
	public static Dish createDefault(DatabaseManager manager) throws SQLException {
		String sql = "INSERT INTO Dish (NAME, CATEGORY, HEALTHINESS, PRICE, DEFAULT_DISCOUNT, LONGTERM_DISCOUNT)" +
				"VALUES ('', null, 1, 0, 0, 0)";
		Dish ret = null;
		try (PreparedStatement ps = manager.prepareStatement(sql, "id")) {
			ps.executeUpdate();
			try (ResultSet rs = ps.getGeneratedKeys()) {
				if (rs.next()) {
					ret = manager.getDish(rs.getInt(1));
				}
			}
		}
		return ret;
	}
	
	@Override
	public void fetch() throws SQLException {
		super.fetch();
		String sql = "SELECT NAME, CATEGORY, HEALTHINESS, PRICE, DEFAULT_DISCOUNT, LONGTERM_DISCOUNT FROM Dish WHERE id = " + id;
		try (PreparedStatement ps = getManager().prepareStatement(sql)) {
			try (ResultSet rs = ps.executeQuery()) {
				if (rs.next()) {
					this.name = rs.getString(1);
					this.category = rs.getString(2);
					this.healthiness = rs.getDouble(3);
					this.price = rs.getDouble(4);
					this.defaultDiscount = rs.getDouble(5);
					this.longtermDiscount = rs.getDouble(6);
				}
			}
		}
	}
	
	/**
	 * Commit the content of this row to the database-table. <br/>
	 * Note: Added and removed resources to a dish are auto-committed, and
	 * 			does not require a execution of this method.
	 */
	@Override
	public void commit() throws SQLException {
		super.commit();
		String sql = "UPDATE Dish SET ";
		sql += "NAME = '" + name + "'";
		if (category == null) {
			sql += ", CATEGORY = NULL";
		}
		else {
			sql += ", CATEGORY = '" + category + "'";
		}
		sql += ", HEALTHINESS = " + healthiness;
		sql += ", PRICE = " + price;
		sql += ", DEFAULT_DISCOUNT = " + defaultDiscount;
		sql += ", LONGTERM_DISCOUNT = " + longtermDiscount;
		sql += " WHERE id = " + id;
		try (PreparedStatement ps = getManager().prepareStatement(sql)) {
			ps.executeUpdate();
		}
	}
	
	@Override
	public void remove() throws SQLException {
		super.remove();
		String sql = "DELETE FROM Dish WHERE id = " + id;
		try (PreparedStatement ps = getManager().prepareStatement(sql)) {
			ps.executeUpdate();
		}
	}
	
	/**
	 * Gets the ID.
	 * @return The ID
	 */
	public int getId() {
		return this.id;
	}
	
	/**
	 * Gets the name.
	 * @return The name
	 * @throws SQLException
	 */
	public String getName() throws SQLException {
		super.tryFetch();
		return name;
	}

	/**
	 * Sets the name to a new value.
	 * @param name The new name
	 */
	public void setName(String name) {
		assert(name != null);				// NOT NULL
		assert(name.length() <= 64);		// Max length = 64
		super.setChanged();
		this.name = name;
	}

	/**
	 * Gets the category.
	 * @return The category
	 */
	public String getCategory() {
		super.tryFetch();
		return category;
	}

	/**
	 * Sets the category to a new value.
	 * @param category The new category
	 */
	public void setCategory(String category) {
		assert(category.length() <= 64);	// Max length = 64
		super.setChanged();
		this.category = category;
	}

	/**
	 * Gets the healthiness.
	 * @return The healthiness
	 */
	public double getHealthiness() {
		super.tryFetch();
		return healthiness;
	}

	/**
	 * Sets the healthiness to a new value.
	 * @param healthiness The new healthiness value
	 */
	public void setHealthiness(double healthiness) {
		super.setChanged();
		this.healthiness = healthiness;
	}

	/**
	 * Gets the price.
	 * @return The price
	 */
	public double getPrice() {
		super.tryFetch();
		return price;
	}

	/**
	 * Sets the price to a new value.
	 * @param price The new price
	 */
	public void setPrice(double price) {
		super.setChanged();
		this.price = price;
	}

	/**
	 * Gets the default discount.
	 * @return The default discount
	 */
	public double getDefaultDiscount() {
		super.tryFetch();
		return defaultDiscount;
	}

	/**
	 * Sets the default discount to a new value.
	 * @param defaultDiscount The new default discount
	 */
	public void setDefaultDiscount(double defaultDiscount) {
		super.setChanged();
		this.defaultDiscount = defaultDiscount;
	}

	/**
	 * Gets the long-term discount.
	 * @return The long-term discount
	 */
	public double getLongtermDiscount() {
		super.tryFetch();
		return longtermDiscount;
	}

	/**
	 * Sets the long-term discount to a new value.
	 * @param longtermDiscount The new long-term discount
	 */
	public void setLongtermDiscount(double longtermDiscount) {
		super.setChanged();
		this.longtermDiscount = longtermDiscount;
	}

	/**
	 * Gets the list of resources linked to this Dish.
	 * @return The list of DishResource
	 */
	public DishResourceList getResources() {
		assert(!isRemoved());
		return resources;
	}

	public boolean equals(Object other) {
		if(other == null || !(other instanceof Dish)) {
			return false;
		}
		return getId() == ((Dish)other).getId();
	}

	public String toString() {
		super.tryFetch();
		return "Dish[name = '" + name + "'; healthiness = " + healthiness
				+ "; price = " + price + "; defaultDiscount = " + defaultDiscount
				+ "; longtermDiscount = " + longtermDiscount + "; resources = "
				+ resources + "]";
	}


}
