package edu.hist.team3.catering.database;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Resource extends DatabaseRow {
	private final int id; 		// id			INT				GENERATED BY DEFAULT AS IDENTITY
	private String name;		// name			VARCHAR(64)		NOT NULL
	private String category;	// category		VARCHAR(64)
	private String description;	// description	VARCHAR(256)
	private String producer;	// producer		VARCHAR(64)
	private String source;		// source		VARCHAR(64)
	private double stockCount;	// stock_count	DOUBLE			NOT NULL
	private double costs;		// costs		DOUBLE
	private double amount;		// amount		DOUBLE
	private double weight;		// weight		DOUBLE
	private double volum;		// volum		DOUBLE
	private double calories;	// calories		DOUBLE
	private double healthiness;	// healthiness	DOUBLE
	
	protected Resource(DatabaseManager manager, int id) {
		super(manager);
		this.id = id;
	}
	
	public static Resource createDefault(DatabaseManager manager) throws SQLException {
		String sql = "INSERT INTO Resource (NAME, CATEGORY, DESCRIPTION, PRODUCER, SOURCE, STOCK_COUNT, COSTS, AMOUNT, WEIGHT, VOLUM, CALORIES, HEALTHINESS)" +
				"VALUES ('', null, null, null, null, 1, 0, 0, 0, 0, 0, 0)";
		Resource ret = null;
		try (PreparedStatement ps = manager.prepareStatement(sql, "id")) {
			ps.executeUpdate();
			try (ResultSet rs = ps.getGeneratedKeys()) {
				if (rs.next()) {
					ret = new Resource(manager, rs.getInt(1));
				}
			}
		}
		return ret;
	}
	
	@Override
	public void fetch() throws SQLException {
		super.fetch();
	}
	
	@Override
	public void commit() throws SQLException {
		super.commit();
	}
	
	@Override
	public void remove() throws SQLException {
		super.remove();
		String sql = "DELETE FROM Resource WHERE id = " + id;
		try (PreparedStatement ps = getManager().prepareStatement(sql)) {
			ps.executeUpdate();
		}
	}

	public String getName() {
		super.tryFetch();
		return name;
	}

	public void setName(String name) {
		assert(name != null);
		assert(name.length() <= 64);
		super.setChanged();
		this.name = name;
	}

	public String getCategory() {
		super.tryFetch();
		return category;
	}

	public void setCategory(String category) {
		assert(category.length() <= 64);
		super.setChanged();
		this.category = category;
	}

	public String getDescription() {
		super.tryFetch();
		return description;
	}

	public void setDescription(String description) {
		assert(description.length() <= 256);
		super.setChanged();
		this.description = description;
	}

	public String getProducer() {
		super.tryFetch();
		return producer;
	}

	public void setProducer(String producer) {
		assert(producer.length() <= 64);
		super.setChanged();
		this.producer = producer;
	}

	public String getSource() {
		super.tryFetch();
		return source;
	}

	public void setSource(String source) {
		assert(source.length() <= 64);
		super.setChanged();
		this.source = source;
	}

	public double getStockCount() {
		super.tryFetch();
		return stockCount;
	}

	public void setStockCount(double stockCount) {
		super.setChanged();
		this.stockCount = stockCount;
	}

	public double getCosts() {
		super.tryFetch();
		return costs;
	}

	public void setCosts(double costs) {
		super.setChanged();
		this.costs = costs;
	}

	public double getAmount() {
		super.tryFetch();
		return amount;
	}

	public void setAmount(double amount) {
		super.setChanged();
		this.amount = amount;
	}

	public double getWeight() {
		super.tryFetch();
		return weight;
	}

	public void setWeight(double weight) {
		super.setChanged();
		this.weight = weight;
	}

	public double getVolum() {
		super.tryFetch();
		return volum;
	}

	public void setVolum(double volum) {
		super.setChanged();
		this.volum = volum;
	}

	public double getCalories() {
		super.tryFetch();
		return calories;
	}

	public void setCalories(double calories) {
		super.setChanged();
		this.calories = calories;
	}

	public double getHealthiness() {
		super.tryFetch();
		return healthiness;
	}

	public void setHealthiness(double healthiness) {
		super.setChanged();
		this.healthiness = healthiness;
	}

	public int getId() {
		super.tryFetch();
		return id;
	}
	
	public boolean equals(Object other) {
		if(other == null || !(other instanceof Resource))
			return false;
		return getId() == ((Resource)other).getId();
	}
	
	public String toString() {
		return "Resource[name = '" + name + "'; category = '"
				+ category + "'; description = '" + description + "'; producer = '"
				+ producer + "'; source = " + source + "; stockCount = "
				+ stockCount + "; costs = " + costs + "; amount = " + amount
				+ "; weight = " + weight + "; volum = " + volum + "; calories = "
				+ calories + "; healthiness = " + healthiness + "]";
	}
}
